datasets:
  IRF3_17028_wk7_env_p_N705_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S508
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17028_wk7_gag_p_N705_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S502
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17038_wk7_env_p_N705_S507:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S507
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17038_wk7_gag_p_N705_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S517
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17041_wk7_env_p_N705_S506:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S506
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17041_wk7_gag_p_N704_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N704
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S508
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
