dataset001:
  template001:
    Forward_Primer_2ndRd_Sequence: AGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    Reverse_Primer_2ndRd_Sequence: AGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTC
    sUMI_Primer_Sequence: actataNNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
    dUMI_Primer_Sequence: NNNNNNNNATAGCTGTCTTTTATC