datasets:
  IRF3_17028_wk7_env_p_N705_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S508
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17028_wk7_gag_p_N705_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S502
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17038_wk7_env_p_N705_S507:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S507
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17038_wk7_gag_p_N705_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S517
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17041_wk7_env_p_N705_S506:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N705
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S506
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17041_wk7_gag_p_N704_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N704
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-03_NIH_B670-IRF3_M4363
    S5_Index: S508
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17012_wk7_env_p_N703_S507:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S507
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17012_wk7_gag_p_N703_S504:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S504
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17013_wk7_env_p_N702_S504:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S504
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17013_wk7_gag_p_N702_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S517
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17014_wk7_env_p_SGA_R03_F08:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F08
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17014_wk7_gag_p_SGA_R03_F04:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F04
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17016_wk7_env_p_SGA_R03_F06:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F06
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17016_wk7_gag_p_SGA_R03_F02:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F02
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17017_wk7_env_p_N701_S504:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S504
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17017_wk7_gag_p_N701_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S517
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17021_wk7_env_p_N702_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S508
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17021_wk7_gag_p_N702_S505:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S505
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17022_wk7_env_p_SGA_R03_F05:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F05
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17022_wk7_gag_p_SGA_R03_F01:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F01
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17023_wk7_env_p_N701_S505:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S505
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17023_wk7_gag_p_N701_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S502
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17024_wk7_env_p_N702_S503:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S503
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17024_wk7_gag_p_N701_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S508
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17025_wk7_env_p_N701_S506:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S506
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17025_wk7_gag_p_N701_S503:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S503
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17026_wk7_env_p_SGA_R04_F05:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F05
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17026_wk7_gag_p_SGA_R03_F12:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F12
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17027_wk7_env_p_SGA_R04_F03:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F03
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17027_wk7_gag_p_SGA_R03_F10:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F10
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17028_wk7_env_p_N703_S503:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-05_UW_H704_M3939
    S5_Index: S503
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17030_wk7_env_p_SGA_R04_F02:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F02
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17030_wk7_gag_p_SGA_R03_F09:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F09
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17032_wk7_env_p_SGA_R04_F04:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F04
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17032_wk7_gag_p_SGA_R03_F11:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F11
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17034_wk7_env_p_N702_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S502
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17034_wk7_gag_p_N701_S507:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N701
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S507
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17035_wk7_env_p_N703_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S502
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17035_wk7_gag_p_N702_S507:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S507
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17036_wk7_env_p_N703_S508:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S508
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17036_wk7_gag_p_N703_S505:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S505
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17037_wk7_env_p_SGA_R03_F07:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F07
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17037_wk7_gag_p_SGA_R03_F03:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F03
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R03
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17038_wk7_env_p_N703_S502:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-05_UW_H704_M3939
    S5_Index: S502
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17040_wk7_env_p_N703_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S517
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17040_wk7_gag_p_N702_S506:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N702
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S506
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17041_wk7_env_p_N703_S517:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-05_UW_H704_M3939
    S5_Index: S517
    sUMI_Primer_Sequence: NNNNNNNNGTATGCTAATTTTTCTCCCTCTTCAGCTG
  IRF3_17042_wk7_env_p_N703_S506:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S506
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17042_wk7_gag_p_N703_S503:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: N703
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-10_NIH_IRF3_M4348
    S5_Index: S503
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
  IRF3_17043_wk7_env_p_SGA_R04_F06:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCGACTAATAGAAAGAGCAGAAGACAGTG
    N7_Index: SGA_F06
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: ACGATCNNNNNNNNTTCAGCTGGGTTTCTCCATGGAGTA
  IRF3_17043_wk7_gag_p_SGA_R04_F01:
    Forward_Primer_2ndRd_Sequence: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    N7_Index: SGA_F01
    Reverse_Primer_2ndRd_Sequence: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    Run: 2019-08_UW_H704_HHV8_IRF3_M4512
    S5_Index: SGA_R04
    sUMI_Primer_Sequence: NNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
