datasets:
  template001:
    Forward_Primer_2ndRd_Sequence: AGATGTGTATAAGAGACAGCCTCCGGTTGCAGGTAAGTGC
    Reverse_Primer_2ndRd_Sequence: AGATGTGTATAAGAGACAGCCGCTCCGTCCGACGACTCACTATA
    sUMI_Primer_Sequence: ANNNNNNNNTTAGAGACATCCCCAGAGCTGTTAG
    dUMI_Primer_Sequence: NNNNNNNN
