name: porpid
dependencies:
  - snakemake-minimal
  - python =3.7
  - pyyaml
  - pandas
  - boto
  - moto
  - filechunkio
  - pysftp
  - requests
  - ftputil
  - XRootD
  - biopython
  - networkx
  - pygraphviz
  - pygments
  - imagemagick
